// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_BatteryPack = NULL;
lv_obj_t * ui_cell5 = NULL;
lv_obj_t * ui_cell8 = NULL;
lv_obj_t * ui_cell10 = NULL;
lv_obj_t * ui_cell11 = NULL;
lv_obj_t * ui_cell15 = NULL;
lv_obj_t * ui_cell14 = NULL;
lv_obj_t * ui_cell13 = NULL;
lv_obj_t * ui_cell16 = NULL;
lv_obj_t * ui_cell7 = NULL;
lv_obj_t * ui_cell9 = NULL;
lv_obj_t * ui_cell12 = NULL;
lv_obj_t * ui_cell6 = NULL;
lv_obj_t * ui_Cell1 = NULL;
lv_obj_t * ui_CELL2 = NULL;
lv_obj_t * ui_cell3 = NULL;
lv_obj_t * ui_cell4 = NULL;
lv_obj_t * ui_GOTOHOME = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_CELL1VAL = NULL;
lv_obj_t * ui_CELL2VAL = NULL;
lv_obj_t * ui_CELL3VAL = NULL;
lv_obj_t * ui_CELL4VAL = NULL;
lv_obj_t * ui_CELL5VAL = NULL;
lv_obj_t * ui_CELL6VAL = NULL;
lv_obj_t * ui_CELL7VAL = NULL;
lv_obj_t * ui_CELL8VAL = NULL;
lv_obj_t * ui_CELL9VAL = NULL;
lv_obj_t * ui_CELL10VAL = NULL;
lv_obj_t * ui_CELL11VAL = NULL;
lv_obj_t * ui_CELL12VAL = NULL;
lv_obj_t * ui_CELL13VAL = NULL;
lv_obj_t * ui_CELL14VAL = NULL;
lv_obj_t * ui_CELL15VAL = NULL;
lv_obj_t * ui_CELL16VAL = NULL;
// event funtions
void ui_event_GOTOHOME(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_HOME, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HOME_screen_init);
    }
}

void ui_event_Label32(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_BatteryPack, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_BatteryPack_screen_init);
    }
}

// build funtions

void ui_BatteryPack_screen_init(void)
{
    ui_BatteryPack = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BatteryPack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BatteryPack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryPack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cell5 = lv_textarea_create(ui_BatteryPack);
    lv_obj_set_width(ui_cell5, 86);
    lv_obj_set_height(ui_cell5, 70);
    lv_obj_set_x(ui_cell5, -297);
    lv_obj_set_y(ui_cell5, -80);
    lv_obj_set_align(ui_cell5, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_cell5, "  cell-5\n");
    lv_textarea_set_placeholder_text(ui_cell5, "Placeholder...");

    ui_cell8 = lv_textarea_create(ui_BatteryPack);
    lv_obj_set_width(ui_cell8, 86);
    lv_obj_set_height(ui_cell8, 70);
    lv_obj_set_x(ui_cell8, 102);
    lv_obj_set_y(ui_cell8, -72);
    lv_obj_set_align(ui_cell8, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_cell8, "  cell-8");
    lv_textarea_set_placeholder_text(ui_cell8, "Placeholder...");

    ui_cell10 = lv_textarea_create(ui_BatteryPack);
    lv_obj_set_width(ui_cell10, 90);
    lv_obj_set_height(ui_cell10, 70);
    lv_obj_set_x(ui_cell10, -32);
    lv_obj_set_y(ui_cell10, 21);
    lv_obj_set_align(ui_cell10, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_cell10, "  cell-10\n");
    lv_textarea_set_placeholder_text(ui_cell10, "Placeholder...");

    ui_cell11 = lv_textarea_create(ui_BatteryPack);
    lv_obj_set_width(ui_cell11, 87);
    lv_obj_set_height(ui_cell11, 70);
    lv_obj_set_x(ui_cell11, -161);
    lv_obj_set_y(ui_cell11, 22);
    lv_obj_set_align(ui_cell11, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_cell11, "  cell-11\n");
    lv_textarea_set_placeholder_text(ui_cell11, "Placeholder...");

    ui_cell15 = lv_textarea_create(ui_BatteryPack);
    lv_obj_set_width(ui_cell15, 85);
    lv_obj_set_height(ui_cell15, 70);
    lv_obj_set_x(ui_cell15, -25);
    lv_obj_set_y(ui_cell15, 125);
    lv_obj_set_align(ui_cell15, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_cell15, "  cell-15\n");
    lv_textarea_set_placeholder_text(ui_cell15, "Placeholder...");

    ui_cell14 = lv_textarea_create(ui_BatteryPack);
    lv_obj_set_width(ui_cell14, 91);
    lv_obj_set_height(ui_cell14, 70);
    lv_obj_set_x(ui_cell14, -156);
    lv_obj_set_y(ui_cell14, 127);
    lv_obj_set_align(ui_cell14, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_cell14, "  cell-14\n");
    lv_textarea_set_placeholder_text(ui_cell14, "Placeholder...");

    ui_cell13 = lv_textarea_create(ui_BatteryPack);
    lv_obj_set_width(ui_cell13, 91);
    lv_obj_set_height(ui_cell13, 70);
    lv_obj_set_x(ui_cell13, -293);
    lv_obj_set_y(ui_cell13, 124);
    lv_obj_set_align(ui_cell13, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_cell13, "  cell-13");
    lv_textarea_set_placeholder_text(ui_cell13, "Placeholder...");

    ui_cell16 = lv_textarea_create(ui_BatteryPack);
    lv_obj_set_width(ui_cell16, 89);
    lv_obj_set_height(ui_cell16, 70);
    lv_obj_set_x(ui_cell16, 112);
    lv_obj_set_y(ui_cell16, 117);
    lv_obj_set_align(ui_cell16, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_cell16, "  cell-16\n");
    lv_textarea_set_placeholder_text(ui_cell16, "Placeholder...");

    ui_cell7 = lv_textarea_create(ui_BatteryPack);
    lv_obj_set_width(ui_cell7, 92);
    lv_obj_set_height(ui_cell7, 70);
    lv_obj_set_x(ui_cell7, -29);
    lv_obj_set_y(ui_cell7, -76);
    lv_obj_set_align(ui_cell7, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_cell7, "  cell-7\n");
    lv_textarea_set_placeholder_text(ui_cell7, "Placeholder...");

    ui_cell9 = lv_textarea_create(ui_BatteryPack);
    lv_obj_set_width(ui_cell9, 94);
    lv_obj_set_height(ui_cell9, 70);
    lv_obj_set_x(ui_cell9, 107);
    lv_obj_set_y(ui_cell9, 19);
    lv_obj_set_align(ui_cell9, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_cell9, "  cell-9");
    lv_textarea_set_placeholder_text(ui_cell9, "Placeholder...");

    ui_cell12 = lv_textarea_create(ui_BatteryPack);
    lv_obj_set_width(ui_cell12, 97);
    lv_obj_set_height(ui_cell12, 70);
    lv_obj_set_x(ui_cell12, -297);
    lv_obj_set_y(ui_cell12, 19);
    lv_obj_set_align(ui_cell12, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_cell12, "  cell-12\n");
    lv_textarea_set_placeholder_text(ui_cell12, "Placeholder...");

    ui_cell6 = lv_textarea_create(ui_BatteryPack);
    lv_obj_set_width(ui_cell6, 94);
    lv_obj_set_height(ui_cell6, 70);
    lv_obj_set_x(ui_cell6, -160);
    lv_obj_set_y(ui_cell6, -74);
    lv_obj_set_align(ui_cell6, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_cell6, "  cell-6\n");
    lv_textarea_set_placeholder_text(ui_cell6, "Placeholder...");

    ui_Cell1 = lv_textarea_create(ui_BatteryPack);
    lv_obj_set_width(ui_Cell1, 83);
    lv_obj_set_height(ui_Cell1, 70);
    lv_obj_set_x(ui_Cell1, 100);
    lv_obj_set_y(ui_Cell1, -171);
    lv_obj_set_align(ui_Cell1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_Cell1, "  cell-1");
    lv_textarea_set_placeholder_text(ui_Cell1, "Placeholder...");

    ui_CELL2 = lv_textarea_create(ui_BatteryPack);
    lv_obj_set_width(ui_CELL2, 90);
    lv_obj_set_height(ui_CELL2, 70);
    lv_obj_set_x(ui_CELL2, -31);
    lv_obj_set_y(ui_CELL2, -174);
    lv_obj_set_align(ui_CELL2, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_CELL2, "  cell-2");
    lv_textarea_set_placeholder_text(ui_CELL2, "Placeholder...");

    ui_cell3 = lv_textarea_create(ui_BatteryPack);
    lv_obj_set_width(ui_cell3, 82);
    lv_obj_set_height(ui_cell3, 70);
    lv_obj_set_x(ui_cell3, -166);
    lv_obj_set_y(ui_cell3, -171);
    lv_obj_set_align(ui_cell3, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_cell3, "  cell-3\n");
    lv_textarea_set_placeholder_text(ui_cell3, "Placeholder...");

    ui_cell4 = lv_textarea_create(ui_BatteryPack);
    lv_obj_set_width(ui_cell4, 88);
    lv_obj_set_height(ui_cell4, 70);
    lv_obj_set_x(ui_cell4, -302);
    lv_obj_set_y(ui_cell4, -170);
    lv_obj_set_align(ui_cell4, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_cell4, "  cell-4\n");
    lv_textarea_set_placeholder_text(ui_cell4, "Placeholder...");

    ui_GOTOHOME = lv_obj_create(ui_BatteryPack);
    lv_obj_set_width(ui_GOTOHOME, 100);
    lv_obj_set_height(ui_GOTOHOME, 50);
    lv_obj_set_x(ui_GOTOHOME, -338);
    lv_obj_set_y(ui_GOTOHOME, 208);
    lv_obj_set_align(ui_GOTOHOME, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GOTOHOME, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel7 = lv_obj_create(ui_BatteryPack);
    lv_obj_set_width(ui_Panel7, 100);
    lv_obj_set_height(ui_Panel7, 50);
    lv_obj_set_x(ui_Panel7, -681);
    lv_obj_set_y(ui_Panel7, -187);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x910A0A), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 11, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel7, LV_BORDER_SIDE_FULL, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_BatteryPack);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, -341);
    lv_obj_set_y(ui_Label32, 209);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "HOME");

    ui_Panel8 = lv_obj_create(ui_BatteryPack);
    lv_obj_set_width(ui_Panel8, 100);
    lv_obj_set_height(ui_Panel8, 50);
    lv_obj_set_x(ui_Panel8, -665);
    lv_obj_set_y(ui_Panel8, -201);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CELL1VAL = lv_label_create(ui_BatteryPack);
    lv_obj_set_width(ui_CELL1VAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CELL1VAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CELL1VAL, 99);
    lv_obj_set_y(ui_CELL1VAL, -159);
    lv_obj_set_align(ui_CELL1VAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CELL1VAL, "0");
    lv_obj_set_style_text_color(ui_CELL1VAL, lv_color_hex(0x17F33D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CELL1VAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CELL1VAL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CELL2VAL = lv_label_create(ui_BatteryPack);
    lv_obj_set_width(ui_CELL2VAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CELL2VAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CELL2VAL, -40);
    lv_obj_set_y(ui_CELL2VAL, -159);
    lv_obj_set_align(ui_CELL2VAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CELL2VAL, "0");
    lv_obj_set_style_text_color(ui_CELL2VAL, lv_color_hex(0x17F33D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CELL2VAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CELL2VAL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CELL3VAL = lv_label_create(ui_BatteryPack);
    lv_obj_set_width(ui_CELL3VAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CELL3VAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CELL3VAL, -168);
    lv_obj_set_y(ui_CELL3VAL, -157);
    lv_obj_set_align(ui_CELL3VAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CELL3VAL, "0");
    lv_obj_set_style_text_color(ui_CELL3VAL, lv_color_hex(0x17F33D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CELL3VAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CELL3VAL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CELL4VAL = lv_label_create(ui_BatteryPack);
    lv_obj_set_width(ui_CELL4VAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CELL4VAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CELL4VAL, -307);
    lv_obj_set_y(ui_CELL4VAL, -156);
    lv_obj_set_align(ui_CELL4VAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CELL4VAL, "0");
    lv_obj_set_style_text_color(ui_CELL4VAL, lv_color_hex(0x17F33D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CELL4VAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CELL4VAL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CELL5VAL = lv_label_create(ui_BatteryPack);
    lv_obj_set_width(ui_CELL5VAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CELL5VAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CELL5VAL, -306);
    lv_obj_set_y(ui_CELL5VAL, -68);
    lv_obj_set_align(ui_CELL5VAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CELL5VAL, "0");
    lv_obj_set_style_text_color(ui_CELL5VAL, lv_color_hex(0x17F33D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CELL5VAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CELL5VAL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CELL6VAL = lv_label_create(ui_BatteryPack);
    lv_obj_set_width(ui_CELL6VAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CELL6VAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CELL6VAL, -163);
    lv_obj_set_y(ui_CELL6VAL, -60);
    lv_obj_set_align(ui_CELL6VAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CELL6VAL, "0");
    lv_obj_set_style_text_color(ui_CELL6VAL, lv_color_hex(0x17F33D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CELL6VAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CELL6VAL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CELL7VAL = lv_label_create(ui_BatteryPack);
    lv_obj_set_width(ui_CELL7VAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CELL7VAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CELL7VAL, -36);
    lv_obj_set_y(ui_CELL7VAL, -67);
    lv_obj_set_align(ui_CELL7VAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CELL7VAL, "0");
    lv_obj_set_style_text_color(ui_CELL7VAL, lv_color_hex(0x17F33D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CELL7VAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CELL7VAL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CELL8VAL = lv_label_create(ui_BatteryPack);
    lv_obj_set_width(ui_CELL8VAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CELL8VAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CELL8VAL, 104);
    lv_obj_set_y(ui_CELL8VAL, -58);
    lv_obj_set_align(ui_CELL8VAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CELL8VAL, "0");
    lv_obj_set_style_text_color(ui_CELL8VAL, lv_color_hex(0x17F33D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CELL8VAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CELL8VAL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CELL9VAL = lv_label_create(ui_BatteryPack);
    lv_obj_set_width(ui_CELL9VAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CELL9VAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CELL9VAL, 102);
    lv_obj_set_y(ui_CELL9VAL, 28);
    lv_obj_set_align(ui_CELL9VAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CELL9VAL, "0");
    lv_obj_set_style_text_color(ui_CELL9VAL, lv_color_hex(0x17F33D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CELL9VAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CELL9VAL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CELL10VAL = lv_label_create(ui_BatteryPack);
    lv_obj_set_width(ui_CELL10VAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CELL10VAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CELL10VAL, -38);
    lv_obj_set_y(ui_CELL10VAL, 34);
    lv_obj_set_align(ui_CELL10VAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CELL10VAL, "0");
    lv_obj_set_style_text_color(ui_CELL10VAL, lv_color_hex(0x17F33D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CELL10VAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CELL10VAL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CELL11VAL = lv_label_create(ui_BatteryPack);
    lv_obj_set_width(ui_CELL11VAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CELL11VAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CELL11VAL, -163);
    lv_obj_set_y(ui_CELL11VAL, 35);
    lv_obj_set_align(ui_CELL11VAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CELL11VAL, "0");
    lv_obj_set_style_text_color(ui_CELL11VAL, lv_color_hex(0x17F33D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CELL11VAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CELL11VAL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CELL12VAL = lv_label_create(ui_BatteryPack);
    lv_obj_set_width(ui_CELL12VAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CELL12VAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CELL12VAL, -308);
    lv_obj_set_y(ui_CELL12VAL, 29);
    lv_obj_set_align(ui_CELL12VAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CELL12VAL, "0");
    lv_obj_set_style_text_color(ui_CELL12VAL, lv_color_hex(0x17F33D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CELL12VAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CELL12VAL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CELL13VAL = lv_label_create(ui_BatteryPack);
    lv_obj_set_width(ui_CELL13VAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CELL13VAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CELL13VAL, -293);
    lv_obj_set_y(ui_CELL13VAL, 136);
    lv_obj_set_align(ui_CELL13VAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CELL13VAL, "0");
    lv_obj_set_style_text_color(ui_CELL13VAL, lv_color_hex(0x17F33D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CELL13VAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CELL13VAL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CELL14VAL = lv_label_create(ui_BatteryPack);
    lv_obj_set_width(ui_CELL14VAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CELL14VAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CELL14VAL, -159);
    lv_obj_set_y(ui_CELL14VAL, 139);
    lv_obj_set_align(ui_CELL14VAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CELL14VAL, "0");
    lv_obj_set_style_text_color(ui_CELL14VAL, lv_color_hex(0x17F33D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CELL14VAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CELL14VAL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CELL15VAL = lv_label_create(ui_BatteryPack);
    lv_obj_set_width(ui_CELL15VAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CELL15VAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CELL15VAL, -23);
    lv_obj_set_y(ui_CELL15VAL, 139);
    lv_obj_set_align(ui_CELL15VAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CELL15VAL, "0");
    lv_obj_set_style_text_color(ui_CELL15VAL, lv_color_hex(0x17F33D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CELL15VAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CELL15VAL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CELL16VAL = lv_label_create(ui_BatteryPack);
    lv_obj_set_width(ui_CELL16VAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CELL16VAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CELL16VAL, 110);
    lv_obj_set_y(ui_CELL16VAL, 126);
    lv_obj_set_align(ui_CELL16VAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CELL16VAL, "0");
    lv_obj_set_style_text_color(ui_CELL16VAL, lv_color_hex(0x17F33D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CELL16VAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CELL16VAL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_GOTOHOME, ui_event_GOTOHOME, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label32, ui_event_Label32, LV_EVENT_ALL, NULL);

}

void ui_BatteryPack_screen_destroy(void)
{
    if(ui_BatteryPack) lv_obj_del(ui_BatteryPack);

    // NULL screen variables
    ui_BatteryPack = NULL;
    ui_cell5 = NULL;
    ui_cell8 = NULL;
    ui_cell10 = NULL;
    ui_cell11 = NULL;
    ui_cell15 = NULL;
    ui_cell14 = NULL;
    ui_cell13 = NULL;
    ui_cell16 = NULL;
    ui_cell7 = NULL;
    ui_cell9 = NULL;
    ui_cell12 = NULL;
    ui_cell6 = NULL;
    ui_Cell1 = NULL;
    ui_CELL2 = NULL;
    ui_cell3 = NULL;
    ui_cell4 = NULL;
    ui_GOTOHOME = NULL;
    ui_Panel7 = NULL;
    ui_Label32 = NULL;
    ui_Panel8 = NULL;
    ui_CELL1VAL = NULL;
    ui_CELL2VAL = NULL;
    ui_CELL3VAL = NULL;
    ui_CELL4VAL = NULL;
    ui_CELL5VAL = NULL;
    ui_CELL6VAL = NULL;
    ui_CELL7VAL = NULL;
    ui_CELL8VAL = NULL;
    ui_CELL9VAL = NULL;
    ui_CELL10VAL = NULL;
    ui_CELL11VAL = NULL;
    ui_CELL12VAL = NULL;
    ui_CELL13VAL = NULL;
    ui_CELL14VAL = NULL;
    ui_CELL15VAL = NULL;
    ui_CELL16VAL = NULL;

}
