// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_BATTERYPACK_H
#define UI_BATTERYPACK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BatteryPack
extern void ui_BatteryPack_screen_init(void);
extern void ui_BatteryPack_screen_destroy(void);
extern lv_obj_t * ui_BatteryPack;
extern lv_obj_t * ui_cell5;
extern lv_obj_t * ui_cell8;
extern lv_obj_t * ui_cell10;
extern lv_obj_t * ui_cell11;
extern lv_obj_t * ui_cell15;
extern lv_obj_t * ui_cell14;
extern lv_obj_t * ui_cell13;
extern lv_obj_t * ui_cell16;
extern lv_obj_t * ui_cell7;
extern lv_obj_t * ui_cell9;
extern lv_obj_t * ui_cell12;
extern lv_obj_t * ui_cell6;
extern lv_obj_t * ui_Cell1;
extern lv_obj_t * ui_CELL2;
extern lv_obj_t * ui_cell3;
extern lv_obj_t * ui_cell4;
extern void ui_event_GOTOHOME(lv_event_t * e);
extern lv_obj_t * ui_GOTOHOME;
extern lv_obj_t * ui_Panel7;
extern void ui_event_Label32(lv_event_t * e);
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_CELL1VAL;
extern lv_obj_t * ui_CELL2VAL;
extern lv_obj_t * ui_CELL3VAL;
extern lv_obj_t * ui_CELL4VAL;
extern lv_obj_t * ui_CELL5VAL;
extern lv_obj_t * ui_CELL6VAL;
extern lv_obj_t * ui_CELL7VAL;
extern lv_obj_t * ui_CELL8VAL;
extern lv_obj_t * ui_CELL9VAL;
extern lv_obj_t * ui_CELL10VAL;
extern lv_obj_t * ui_CELL11VAL;
extern lv_obj_t * ui_CELL12VAL;
extern lv_obj_t * ui_CELL13VAL;
extern lv_obj_t * ui_CELL14VAL;
extern lv_obj_t * ui_CELL15VAL;
extern lv_obj_t * ui_CELL16VAL;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

