// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Label1;
lv_obj_t * ui_HOME = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Gear = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_OdoMeterVal = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_SOC = NULL;
lv_obj_t * ui_SOCVal = NULL;
lv_obj_t * ui_Speed = NULL;
lv_obj_t * ui_SpeedVal = NULL;
lv_obj_t * ui_SpeedKmh = NULL;
lv_obj_t * ui_DriveMode = NULL;
lv_obj_t * ui_VOLTAGE = NULL;
lv_obj_t * ui_VOLVAL = NULL;
lv_obj_t * ui_ChargeDischargeCurrent = NULL;
lv_obj_t * ui_ChargeDischargeCurrrentVal = NULL;
lv_obj_t * ui_MotorTemp = NULL;
lv_obj_t * ui_MotorTempValue = NULL;
lv_obj_t * ui_MCUTemp = NULL;
lv_obj_t * ui_MCUTempVal = NULL;
lv_obj_t * ui_RPM = NULL;
lv_obj_t * ui_RPMVal = NULL;
lv_obj_t * ui_MCUFault = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_MCUFAULTDETECTION = NULL;
lv_obj_t * ui_Cellvoltages = NULL;
// event funtions
void ui_event_Panel9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_BatteryPack, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_BatteryPack_screen_init);
    }
}

// build funtions

void ui_HOME_screen_init(void)
{
    ui_HOME = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HOME, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME, lv_color_hex(0x0F0E0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_HOME, lv_color_hex(0x0B0B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_HOME, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_HOME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_Panel4, 234);
    lv_obj_set_height(ui_Panel4, 224);
    lv_obj_set_x(ui_Panel4, -260);
    lv_obj_set_y(ui_Panel4, 86);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 158, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel4, lv_color_hex(0x4CD3F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel4, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_Panel6, 233);
    lv_obj_set_height(ui_Panel6, 216);
    lv_obj_set_x(ui_Panel6, 260);
    lv_obj_set_y(ui_Panel6, 80);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 158, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel6, lv_color_hex(0x4CD3F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel6, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_Panel1, 158);
    lv_obj_set_height(ui_Panel1, 158);
    lv_obj_set_x(ui_Panel1, -262);
    lv_obj_set_y(ui_Panel1, 87);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 158, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_Panel2, 158);
    lv_obj_set_height(ui_Panel2, 158);
    lv_obj_set_x(ui_Panel2, 260);
    lv_obj_set_y(ui_Panel2, 81);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 158, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel2, lv_color_hex(0x4CD3F7), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_Panel5, 164);
    lv_obj_set_height(ui_Panel5, 171);
    lv_obj_set_x(ui_Panel5, 6);
    lv_obj_set_y(ui_Panel5, 97);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 158, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel5, lv_color_hex(0x4CD3F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel5, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_Panel3, 130);
    lv_obj_set_height(ui_Panel3, 132);
    lv_obj_set_x(ui_Panel3, 9);
    lv_obj_set_y(ui_Panel3, 98);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 158, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x070707), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel3, lv_color_hex(0x4CD3F7), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gear = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Gear, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Gear, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Gear, 6);
    lv_obj_set_y(ui_Gear, 211);
    lv_obj_set_align(ui_Gear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Gear, "GEAR");
    lv_obj_set_style_text_font(ui_Gear, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 277);
    lv_obj_set_y(ui_Label3, 215);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "ODO ");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xD80D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OdoMeterVal = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_OdoMeterVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OdoMeterVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OdoMeterVal, 255);
    lv_obj_set_y(ui_OdoMeterVal, 64);
    lv_obj_set_align(ui_OdoMeterVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OdoMeterVal, "0");
    lv_obj_set_style_text_font(ui_OdoMeterVal, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 266);
    lv_obj_set_y(ui_Label5, 121);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Km");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOC = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_SOC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SOC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SOC, -13);
    lv_obj_set_y(ui_SOC, -129);
    lv_obj_set_align(ui_SOC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOC, " SOC           :          %   ");
    lv_obj_set_style_text_color(ui_SOC, lv_color_hex(0xF96714), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SOC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SOC, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOCVal = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_SOCVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SOCVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SOCVal, 40);
    lv_obj_set_y(ui_SOCVal, -127);
    lv_obj_set_align(ui_SOCVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOCVal, "0");
    lv_obj_set_style_text_font(ui_SOCVal, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Speed = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Speed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Speed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Speed, -262);
    lv_obj_set_y(ui_Speed, 215);
    lv_obj_set_align(ui_Speed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Speed, "SPEED");
    lv_obj_set_style_text_color(ui_Speed, lv_color_hex(0xE21533), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Speed, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedVal = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_SpeedVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedVal, -258);
    lv_obj_set_y(ui_SpeedVal, 80);
    lv_obj_set_align(ui_SpeedVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedVal, "0");
    lv_obj_set_style_text_color(ui_SpeedVal, lv_color_hex(0xF7F1F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedVal, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedKmh = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_SpeedKmh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedKmh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedKmh, -258);
    lv_obj_set_y(ui_SpeedKmh, 138);
    lv_obj_set_align(ui_SpeedKmh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedKmh, "Km/h");
    lv_obj_set_style_text_font(ui_SpeedKmh, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DriveMode = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_DriveMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DriveMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DriveMode, 5);
    lv_obj_set_y(ui_DriveMode, 96);
    lv_obj_set_align(ui_DriveMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DriveMode, "N");
    lv_obj_set_style_text_font(ui_DriveMode, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VOLTAGE = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_VOLTAGE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VOLTAGE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VOLTAGE, -301);
    lv_obj_set_y(ui_VOLTAGE, -212);
    lv_obj_set_align(ui_VOLTAGE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VOLTAGE, "VOLTEGE  :            V");
    lv_obj_set_style_text_color(ui_VOLTAGE, lv_color_hex(0x1EF235), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VOLTAGE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VOLTAGE, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VOLVAL = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_VOLVAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VOLVAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VOLVAL, -253);
    lv_obj_set_y(ui_VOLVAL, -208);
    lv_obj_set_align(ui_VOLVAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VOLVAL, "0");
    lv_obj_set_style_text_font(ui_VOLVAL, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChargeDischargeCurrent = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_ChargeDischargeCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargeDischargeCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeDischargeCurrent, -3);
    lv_obj_set_y(ui_ChargeDischargeCurrent, -190);
    lv_obj_set_align(ui_ChargeDischargeCurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargeDischargeCurrent, "CHARGE\nDISCHARGE\nCURRENT       :              A        ");
    lv_obj_set_style_text_color(ui_ChargeDischargeCurrent, lv_color_hex(0x10F71A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargeDischargeCurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargeDischargeCurrent, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChargeDischargeCurrrentVal = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_ChargeDischargeCurrrentVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargeDischargeCurrrentVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeDischargeCurrrentVal, 44);
    lv_obj_set_y(ui_ChargeDischargeCurrrentVal, -172);
    lv_obj_set_align(ui_ChargeDischargeCurrrentVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargeDischargeCurrrentVal, "0");
    lv_obj_set_style_text_font(ui_ChargeDischargeCurrrentVal, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorTemp = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_MotorTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorTemp, -299);
    lv_obj_set_y(ui_MotorTemp, -154);
    lv_obj_set_align(ui_MotorTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorTemp, "MOTOR\nTEMP     :          C");
    lv_obj_set_style_text_color(ui_MotorTemp, lv_color_hex(0xEF4C0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorTemp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorTempValue = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_MotorTempValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorTempValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorTempValue, -255);
    lv_obj_set_y(ui_MotorTempValue, -145);
    lv_obj_set_align(ui_MotorTempValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorTempValue, "0");
    lv_obj_set_style_text_font(ui_MotorTempValue, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MCUTemp = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_MCUTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MCUTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MCUTemp, -300);
    lv_obj_set_y(ui_MCUTemp, -82);
    lv_obj_set_align(ui_MCUTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MCUTemp, "MCU\nTEMP      :         C");
    lv_obj_set_style_text_color(ui_MCUTemp, lv_color_hex(0x05E31D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MCUTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MCUTemp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MCUTempVal = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_MCUTempVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MCUTempVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MCUTempVal, -250);
    lv_obj_set_y(ui_MCUTempVal, -70);
    lv_obj_set_align(ui_MCUTempVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MCUTempVal, "0");
    lv_obj_set_style_text_font(ui_MCUTempVal, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPM = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_RPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPM, -68);
    lv_obj_set_y(ui_RPM, -74);
    lv_obj_set_align(ui_RPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RPM, " RPM         :");
    lv_obj_set_style_text_color(ui_RPM, lv_color_hex(0x07FA0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPM, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMVal = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_RPMVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPMVal, 69);
    lv_obj_set_y(ui_RPMVal, -75);
    lv_obj_set_align(ui_RPMVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RPMVal, "0");
    lv_obj_set_style_text_font(ui_RPMVal, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MCUFault = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_MCUFault, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MCUFault, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MCUFault, 228);
    lv_obj_set_y(ui_MCUFault, -99);
    lv_obj_set_align(ui_MCUFault, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MCUFault, "MCU\nFAULT :");
    lv_obj_set_style_text_color(ui_MCUFault, lv_color_hex(0x0FF12F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MCUFault, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MCUFault, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_Panel9, 100);
    lv_obj_set_height(ui_Panel9, 50);
    lv_obj_set_x(ui_Panel9, 329);
    lv_obj_set_y(ui_Panel9, -206);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MCUFAULTDETECTION = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_MCUFAULTDETECTION, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MCUFAULTDETECTION, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MCUFAULTDETECTION, 316);
    lv_obj_set_y(ui_MCUFAULTDETECTION, -89);
    lv_obj_set_align(ui_MCUFAULTDETECTION, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MCUFAULTDETECTION, "NO");
    lv_obj_set_style_text_font(ui_MCUFAULTDETECTION, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cellvoltages = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Cellvoltages, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Cellvoltages, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Cellvoltages, 333);
    lv_obj_set_y(ui_Cellvoltages, -204);
    lv_obj_set_align(ui_Cellvoltages, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Cellvoltages, "Cell_Voltages");

    lv_obj_add_event_cb(ui_Panel9, ui_event_Panel9, LV_EVENT_ALL, NULL);
    uic_Label1 = ui_Gear;

}

void ui_HOME_screen_destroy(void)
{
    if(ui_HOME) lv_obj_del(ui_HOME);

    // NULL screen variables
    ui_HOME = NULL;
    ui_Panel4 = NULL;
    ui_Panel6 = NULL;
    ui_Panel1 = NULL;
    ui_Panel2 = NULL;
    ui_Panel5 = NULL;
    ui_Panel3 = NULL;
    uic_Label1 = NULL;
    ui_Gear = NULL;
    ui_Label3 = NULL;
    ui_OdoMeterVal = NULL;
    ui_Label5 = NULL;
    ui_SOC = NULL;
    ui_SOCVal = NULL;
    ui_Speed = NULL;
    ui_SpeedVal = NULL;
    ui_SpeedKmh = NULL;
    ui_DriveMode = NULL;
    ui_VOLTAGE = NULL;
    ui_VOLVAL = NULL;
    ui_ChargeDischargeCurrent = NULL;
    ui_ChargeDischargeCurrrentVal = NULL;
    ui_MotorTemp = NULL;
    ui_MotorTempValue = NULL;
    ui_MCUTemp = NULL;
    ui_MCUTempVal = NULL;
    ui_RPM = NULL;
    ui_RPMVal = NULL;
    ui_MCUFault = NULL;
    ui_Panel9 = NULL;
    ui_MCUFAULTDETECTION = NULL;
    ui_Cellvoltages = NULL;

}
