// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HOME
extern void ui_HOME_screen_init(void);
extern void ui_HOME_screen_destroy(void);
extern lv_obj_t * ui_HOME;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Gear;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_OdoMeterVal;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_SOC;
extern lv_obj_t * ui_SOCVal;
extern lv_obj_t * ui_Speed;
extern lv_obj_t * ui_SpeedVal;
extern lv_obj_t * ui_SpeedKmh;
extern lv_obj_t * ui_DriveMode;
extern lv_obj_t * ui_VOLTAGE;
extern lv_obj_t * ui_VOLVAL;
extern lv_obj_t * ui_ChargeDischargeCurrent;
extern lv_obj_t * ui_ChargeDischargeCurrrentVal;
extern lv_obj_t * ui_MotorTemp;
extern lv_obj_t * ui_MotorTempValue;
extern lv_obj_t * ui_MCUTemp;
extern lv_obj_t * ui_MCUTempVal;
extern lv_obj_t * ui_RPM;
extern lv_obj_t * ui_RPMVal;
extern lv_obj_t * ui_MCUFault;
extern void ui_event_Panel9(lv_event_t * e);
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_MCUFAULTDETECTION;
extern lv_obj_t * ui_Cellvoltages;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Label1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

